### ISSUE TITLE
IndexOutOfRangeException when parsing .NET 4.0 components

### ISSUE THREAD

**Issue by ProgTrade** [geaz/sharpDox#91]
Hi,

I get this exception with all projects that I tried (targeting .NET 4.0; translated from German into English):

`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SharpDox.Build.Roslyn.Parser.ProjectParser.SeeParser.ResolveAllSeeTokens()
   at SharpDox.Build.Roslyn.RoslynParser.ResolveSeeTokens(ParserOptions parserOptions)
   at SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls)
   at SharpDox.Build.Context.Step.StructeParseCodeStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()`

I've noticed that this happens when it processes the .NET 4.0 components. The projects themselves seem to be completely fine. I also tried several builds linked in other/similar issues that I found here on GitHub. Unfortunately, none of them worked neither.

Best,
Dominic

**Comment by geaz** [comment]
Hi Dominic,

will check this issue in the next few days. Just returned from vacation :)

**Comment by geaz** [comment]
Is the project, you tried to build, open source?

**Comment by ProgTrade** [comment]
Hi, 

alright, no problem. I know that. :D
I've seen that you've asked in a further comment, if the project is open source. So, if you want to reproduce it maybe using the project, you can find it here: https://github.com/ProgTrade/nUpdate (master)

Best,
Dominic

**Comment by geaz** [comment]
I saw, that this bug was already fixed in a past commit. I will try to release a new version today which will fix your issue.

**Comment by ProgTrade** [comment]
Okay, I thought so as well, but it seems there is still a problem. :D Did you maybe override the master with commits that excluded this fix again?
Anyway, thanks for your help. :)

**Comment by geaz** [comment]
The fixes are just in the dev branch at the moment.
